name: Build

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14"
      - uses: actions/checkout@v2
      - name: xcodebuild
        run: xcodebuild -scheme SwiftUISupport -sdk iphoneos
  test:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14"
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Test
        run: xcodebuild -scheme SwiftUISupportTests -resultBundlePath results/SwiftUISupportTests.xcresult test -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.5' -derivedDataPath ./DerivedData | xcpretty

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: |
            results/SwiftUISupportTests.xcresult
        if: success() || failure()
